create table if not exists public.reservations (
  id bigint generated by default as identity primary key,
  device_id text not null unique,
  nickname text not null check (char_length(nickname) between 1 and 20),
  party_size integer not null check (party_size between 1 and 20),
  visit_date date not null,
  visit_time text not null,
  seating text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (char_length(email) between 3 and 254),
  created_at timestamptz not null default now()
);

alter table public.reservations enable row level security;
alter table public.newsletter_subscribers enable row level security;

drop policy if exists "anyone can count reservations" on public.reservations;
drop policy if exists "anyone can create one device reservation" on public.reservations;
drop policy if exists "visitors can submit newsletter email" on public.newsletter_subscribers;
drop policy if exists "hidden console can read newsletter emails" on public.newsletter_subscribers;

create policy "anyone can count reservations"
on public.reservations for select
to anon
using (true);

create policy "anyone can create one device reservation"
on public.reservations for insert
to anon
with check (true);

create policy "visitors can submit newsletter email"
on public.newsletter_subscribers for insert
to anon
with check (true);

create policy "hidden console can read newsletter emails"
on public.newsletter_subscribers for select
to anon
using (true);
